#!/bin/bash

source build.cfg
mkdir $BUILD
python3 src/main.py $FILENAME.narda -o $BUILD/$FILENAME.asm
nasm -F dwarf -f elf64 $BUILD/$FILENAME.asm -o $BUILD/$FILENAME.o
ld -o $BUILD/$FILENAME $BUILD/$FILENAME.o
